[package]
name = "simple-home-dir"
version = "0.1.7"
edition = "2021"

license = "MIT"
repository = "https://github.com/splurf/simple-home-dir"
authors = ["Evan Schwartzentruber <evandotschwartzentruber@gmail.com>"]
description = "An extremely small and simple library purposed to retrieve the user's home directory."
keywords = ["home", "directory", "tilde"]
categories = ["accessibility"]

[profile.release]
strip = true
opt-level = "z"
lto = "thin"

[dependencies.dirs]
version = "5.0.1"
default-features = false
optional = true

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.48.0"
default-features = false
features = ["Win32_System_Com_CallObj", "Win32_Foundation", "Win32_Globalization", "Win32_UI_Shell_Common"]

[features]
test = ["dirs", "expand_tilde"]
expand_tilde = []