[package]
name = "simple-home-dir"
version = "0.3.5"
edition = "2021"

license = "MIT"
repository = "https://github.com/splurf/simple-home-dir"
authors = ["Evan Schwartzentruber <evandotschwartzentruber@gmail.com>"]
description = "Efficiently retrieve the user's home directory."
keywords = ["home", "directory", "fast", "path", "lightweight"]
categories = ["accessibility"]

[dev-dependencies.dirs]
version = "5.0.1"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.52.0"
features = ["Win32_Foundation", "Win32_Globalization", "Win32_System", "Win32_System_Com", "Win32_UI", "Win32_UI_Shell"]

[profile.release]
lto = "thin"
codegen-units = 1